<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LP398" failures="5" tests="5" name="com.sample.tests.PositiveTest" time="7.596" errors="0" timestamp="06 Aug 2024 12:07:18 GMT" skipped="0">
  <testcase classname="com.sample.tests.PositiveTest" name="testPizzaType" time="1.477">
    <failure message="The following asserts failed:
	Topping 1 dropdown is not reset. expected [Choose a Toppings 1] but found [Mozzarella cheese],
	Topping 2 dropdown is not reset. expected [Choose a Toppings 2] but found [Olives]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Topping 1 dropdown is not reset. expected [Choose a Toppings 1] but found [Mozzarella cheese],
Topping 2 dropdown is not reset. expected [Choose a Toppings 2] but found [Olives]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.sample.pages.PizzaPage.checkForm(PizzaPage.java:238)
at com.sample.tests.PositiveTest.testPizzaType(PositiveTest.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
    </failure>
  </testcase> <!-- testPizzaType -->
  <testcase classname="com.sample.tests.PositiveTest" name="testPizzaType" time="1.358">
    <failure message="The following asserts failed:
	Topping 1 dropdown is not reset. expected [Choose a Toppings 1] but found [Mozzarella cheese],
	Topping 2 dropdown is not reset. expected [Choose a Toppings 2] but found [Olives]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Topping 1 dropdown is not reset. expected [Choose a Toppings 1] but found [Mozzarella cheese],
Topping 2 dropdown is not reset. expected [Choose a Toppings 2] but found [Olives]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.sample.pages.PizzaPage.checkForm(PizzaPage.java:238)
at com.sample.tests.PositiveTest.testPizzaType(PositiveTest.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
    </failure>
  </testcase> <!-- testPizzaType -->
  <testcase classname="com.sample.tests.PositiveTest" name="testPizzaType" time="1.556">
    <failure message="The following asserts failed:
	Topping 1 dropdown is not reset. expected [Choose a Toppings 1] but found [Mozzarella cheese],
	Topping 2 dropdown is not reset. expected [Choose a Toppings 2] but found [Olives]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Topping 1 dropdown is not reset. expected [Choose a Toppings 1] but found [Mozzarella cheese],
Topping 2 dropdown is not reset. expected [Choose a Toppings 2] but found [Olives]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.sample.pages.PizzaPage.checkForm(PizzaPage.java:238)
at com.sample.tests.PositiveTest.testPizzaType(PositiveTest.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
    </failure>
  </testcase> <!-- testPizzaType -->
  <testcase classname="com.sample.tests.PositiveTest" name="testPizzaType" time="1.896">
    <failure message="The following asserts failed:
	Topping 1 dropdown is not reset. expected [Choose a Toppings 1] but found [Mozzarella cheese],
	Topping 2 dropdown is not reset. expected [Choose a Toppings 2] but found [Olives]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Topping 1 dropdown is not reset. expected [Choose a Toppings 1] but found [Mozzarella cheese],
Topping 2 dropdown is not reset. expected [Choose a Toppings 2] but found [Olives]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.sample.pages.PizzaPage.checkForm(PizzaPage.java:238)
at com.sample.tests.PositiveTest.testPizzaType(PositiveTest.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
    </failure>
  </testcase> <!-- testPizzaType -->
  <testcase classname="com.sample.tests.PositiveTest" name="testPizzaType" time="1.309">
    <failure message="The following asserts failed:
	Topping 1 dropdown is not reset. expected [Choose a Toppings 1] but found [Mozzarella cheese],
	Topping 2 dropdown is not reset. expected [Choose a Toppings 2] but found [Olives]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Topping 1 dropdown is not reset. expected [Choose a Toppings 1] but found [Mozzarella cheese],
Topping 2 dropdown is not reset. expected [Choose a Toppings 2] but found [Olives]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.sample.pages.PizzaPage.checkForm(PizzaPage.java:238)
at com.sample.tests.PositiveTest.testPizzaType(PositiveTest.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
    </failure>
  </testcase> <!-- testPizzaType -->
</testsuite> <!-- com.sample.tests.PositiveTest -->
